---

# This determines the default island generator when users don't specify which generator to use.
# Available options: basic, legacy
# If this option is missing, or set incorrectly, the plugin will default to basic.
default-generator: basic


enable-teamchat: true

# Place the folder names of worlds that you do not want to be deleted when the cleanup command is used.
# If this is left empty, the cleanup command will not work.  Example: [world, lobby, pvp, shop]
protected-worlds: []


# This will modify the contents of the starter chest for new islands.  If you put more than 27 entries
# the plugin will only use the first 27 and the rest will be ignored.  If no items are found in the
# config, a set of default items will be used instead.
starting-items:
  - id: 9
    meta: 0
    quantity: 2
  - id: 11
    meta: 0
    quantity: 1
  - id: 79
    meta: 0
    quantity: 2
  - id: 103
    meta: 0
    quantity: 1
  - id: 352
    meta: 0
    quantity: 1
  - id: 361
    meta: 0
    quantity: 1
  - id: 81
    meta: 0
    quantity: 1
  - id: 83
    meta: 0
    quantity: 1
  - id: 297
    meta: 0
    quantity: 1
  - id: 296
    meta: 0
    quantity: 1
  - id: 298
    meta: 0
    quantity: 1
  - id: 299
    meta: 0
    quantity: 1
  - id: 300
    meta: 0
    quantity: 1
  - id: 301
    meta: 0
    quantity: 1



# This modifies the items that users will find by mining cobblestone.  To set the chance option, use
# a number greater than 0.  The higher the number, the more likely it will be that the player will
# get that item compared to an item with a lower number.
cobble-drops:
  - id: 264
    meta: 0
    chance: 1
  - id: 265
    meta: 0
    chance: 3
  - id: 266
    meta: 0
    chance: 10
  - id: 21
    meta: 0
    chance: 20
  - id: 263
    meta: 0
    chance: 40
  - id: 4
    meta: 0
    chance: 74
...